### ISSUE TITLE
Releasing resolved object on the constructor

### ISSUE THREAD

**Issue by hikalkan** [castleproject/Windsor#100]
If we Resolve an object in the constructor, castle automatically releases the resolved object when parent object is released.

This test fails since MyDisposableClass is released by windsor.

``` C#
    public class ConstructorResolveTests: TestBaseWithLocalIocManager
    {
        private readonly WindsorContainer _container;

        public ConstructorResolveTests()
        {
            _container = new WindsorContainer();

            _container.Register(
                Component.For<MyDisposableClass>().LifestyleTransient(),
                Component.For<MyClient>().LifestyleTransient()
                );
        }

        [Fact]
        public void Should_Not_Release_MyDisposableClass()
        {
            var client = _container.Resolve<MyClient>();
            _container.Release(client);

            MyDisposableClass.DisposeCount.ShouldBe(0); //But it is 1
        }

        public class MyClient
        {
            private readonly MyDisposableClass _myDisposableObject;

            public MyClient(IKernel kernel)
            {
                _myDisposableObject = kernel.Resolve<MyDisposableClass>();
            }
        }

        public class MyDisposableClass : IDisposable
        {
            public static int DisposeCount { get; set; }

            public void Dispose()
            {
                DisposeCount++;
            }
        }
    }
```

This is unexpected by me. Because, Resolving was done in a deeper level and I hardly find the actual reason. While this seems reasonable in some cases, it may not be proper always. Can we change this behaviour?

Thanks.

**Comment by IanYates** [comment]
That does look surprising.  Given the test fails, and I've only run through the code in my head, the only thing that comes to mind is that the IKernel being passed in to MyClient's constructor is a child container created for the lifetime of the MyClient instance, and when that MyClient instance is released, the child IKernel is getting released too (as you'd expect since it was created for the MyClient).

If you step through the test in the debugger could you check to see if the IKernel in MyClient indicates it's a child kernel or if it's the same kernel as _container's kernel?

Could you expand on your use-case a little bit?  I'm guessing that MyClient's resolved instance of MyDisposableClass should outlive the MyClient instance because that MyDisposableClass reference is being passed on to something else that MyClient creates as a long-lived 'thing'.  Assuming that you don't want MyDisposableClass to be a singleton, could a typed factory be better for you here?

**Comment by jonorossi** [comment]
That is working as expected, Windsor doesn't know that you resolved `MyDisposableClass` inside the constructor of `MyClient` if you call `Resolve` explicitly, you could have easily called another function in another class which caused Resolve to be called.

The Windsor rule is, if you call Resolve you have to call Release (https://github.com/castleproject/Windsor/blob/master/docs/release-policy.md#default-policy). `MyClient` should either let Windsor provide the dependency via the constructor parameters, or Resolve+Release the component from the container (preferably via a factory rather than using the `IKernel` directly).

FYI, child containers are explicit, Windsor won't create a child container for you, Windsor internally will use a `CreationContext` to keep track of where it is creating your components.

**Comment by IanYates** [comment]
@jonorossi - I completely agree.  What I couldn't see from reading through the code though is how the `Dispose()` on `MyDisposableClass` is getting called, causing the test to fail?   (unless there's more code that's not being shown somewhere)

I've followed the principle of not resolving more than once so typed factories are used throughout my code rather than passing around the kernel so I've never really tried this scenario before.

To satisfy curiosity...
I just copied the code into Linqpad and referenced the Windsor Nuget package.  It reproduces in there too from what I can tell.
Stepping through the code I can see that after `_container.Resolve<MyClient>()`, the kernel's `ReleasePolicy` has 2 tracked objects, as you'd expect.  However the burden for the `MyClient` instance has a dependency stored against the burden for `MyDisposableClass`.  I wouldn't expect that to be the case.

Stepping back....  Could it just be that, because the class implementing `IKernel` also implements `IDisposable`, when your `MyClient` instance is released, the `IKernel` instance supplied to it, which happens to be your main Windsor kernel, is also released?  In doing so, any other resolved instances, such as the instance of `MyDisposableClass` is also released as you'd expect.  At first blush this sounds reasonable (if initially surprising to those expecting to use Windsor as a service locator).

However, if I change the sample code so it's effectively like

    public class ConstructorResolveTests: TestBaseWithLocalIocManager
    {
        private readonly WindsorContainer _container;

        public ConstructorResolveTests()
        {
            _container = new WindsorContainer();

            _container.Register(
                Component.For<MyDisposableClass>().LifestyleTransient(),
                Component.For<MyClient>().LifestyleTransient()
                );
        }

        [Fact]
        public void Should_Not_Release_MyDisposableClass()
        {
            var client = _container.Resolve<MyClient>();
            var disp  = _container.Resolve<MyDisposableClass>();  //CHANGED
            _container.Release(client);

            MyDisposableClass.DisposeCount.ShouldBe(0); //But it is 1
        }

        public class MyClient
        {
            //COMMENTED OUT
            //private readonly MyDisposableClass _myDisposableObject;

            public MyClient(IKernel kernel)    //Still accepting the IKernel
            {
                //COMMENTED OUT
                //_myDisposableObject = kernel.Resolve<MyDisposableClass>();
            }
        }

        public class MyDisposableClass : IDisposable
        {
            public static int DisposeCount { get; set; }

            public void Dispose()
            {
                DisposeCount++;
            }
        }
    }

There's no error, which implies the IKernel instance is NOT being disposed.

The short answer is to use a typed factory since this scenario is what they're designed for.  However I'd like to still understand the underlying reason for the disposal in this case.  Apologies @jonorossi for the long post but I'm not sure your answer addresses the issue.

Also, @hikalkan - what's in the `TestBaseWithLocalIocManager` class?

**Comment by jonorossi** [comment]
@IanYates correct `IKernel` won't get disposed, Windsor knows about this type which is why you don't have to register it.

My bad, I misread this line as maintaining a list of alive objects:
```
MyDisposableClass.DisposeCount.ShouldBe(0); //But it is 1
```

It has been a while since I've worked in the guts of Windsor so I was wrong, Windsor will actually track that explicit resolution as a dependency of `MyClient` as you have found:

* `DefaultKernel.ResolveComponent` will switch the current creation context with its own that points at the parent as expected, because the resolution of these two instances are nested: https://github.com/castleproject/Windsor/blob/master/src/Castle.Windsor/MicroKernel/DefaultKernel.cs#L708
* `CreationContext.ExitResolutionContext` is what is adding that dependency to the `MyClient` burden as the `ResolutionContext` is disposed: https://github.com/castleproject/Windsor/blob/master/src/Castle.Windsor/MicroKernel/Context/CreationContext.cs#L399
* `Burden.Release` as you've probably already seen is the one releasing the `MyDisposableClass ` dependency: https://github.com/castleproject/Windsor/blob/master/src/Castle.Windsor/MicroKernel/Burden.cs#L132

**Comment by IanYates** [comment]
Thanks @jonorossi.  I was gravitating towards some sort of creation context going on but am not familiar enoguh with the guts of the Castle code to really dig around (and this thread was me procrastinating at work already!).  Thanks for confirming my suspicions.  As I said, I hadn't used Windsor that way as I didn't realise it implicitly registered IKernel but the behaviour makes some sense.

@hikalkan - I suspect, as it's known behaviour (although possibly not well documented), it won't get changed.  An unknown number of people are relying on it and it has been specifically coded in to Windsor.  
So my suggestion is to use a typed factory and pass that around.  It'd be interesting to see if invoking the typed factory from within your constructor also creates the disposal dependency.  I don't have enough procrastination time left today to investigate :D.  
Other choices are to register your other class as a singleton (not sure if that's suitable for you), or register the class by providing an instantiation function and flag it as externally managed so that Windsor won't track it for release (but then you need to dispose it yourself).

**Comment by jonorossi** [comment]
Yep, it has been this way for over 5 years so I doubt we'll change it. We should definitely get something into the docs so this isn't unexpected to users as it wasn't obvious to me why this was occurring until I read the code.

**Comment by hikalkan** [comment]
@IanYates, TestBaseWithLocalIocManager is nothing and has no effect here (Nothing changes when I remove it). Don't mind it. 

I can not do it singleton. Actually, the case is that: I used a factory, and called that factory inside the constructor. Somehow Windsor knows that and it releases it automatically. I copy the related part of the  actual code:

````C#
public class MyService //this class is Transient
{
    private readonly ICache _cache; //ICache is Transient

    public MyService(ICacheManager cacheManager) //ICacheManager is singleton!
    {
        _cache = cacheManager.GetCache("MyCache"); //Cache manager creates the ICache by resolving from IOC.
    }

    //... other methods using _cache
}
````

I use a singleton ICacheManager to get a named ICache object. CacheManager creates an ICache and stores in a dictionary interlally. If it does exists, just returns the ICache instead of creating a new one (So, we can say it caches the caches).

Since MyService is is transient, it is released when request complete. And it also releases the ICache! But I don't want that. Probably, not you did understand the real situation. It was hard for me to find that's related to Windsor :)

**Comment by IanYates** [comment]
Ok - this was too interesting so I procrastinated some more :watch: 

For others stumbling across this, here are some other pertinent facts

a) The `IKernel` passed in seems to be the very same instance of the `IKernel` in the `WindsorContainer`'s `Kernel` property
b) Avoiding passing in an `IKernel` and instead accessing some global copy of the container (classic service locator usage :warning:) still triggers the relationship (aka "burden") and thus the unwanted disposal
c) Stashing a copy of the given `IKernel` and using it *outside* of the constructor to create an instance, does not create any relationship/burden.  Seeing that (a) is true, this is not surprising.
d) Typed Factories do *not* change this behaviour at all.  That is, passing a typed factory into a constructor and invoking a creation method on that factory from within the constructor will also create a relationship/burden.
e) Extra tricks like using IInitializable (see https://github.com/castleproject/Windsor/blob/master/docs/lifecycle.md) also play into the construction process  (aka "component commission") so kernel usage here, either directly or via a typed factory, triggers a relationship/burden

Looking at the docs, and thinking about the various extra options you get during component registration, the behaviour can only be this way.  Picture one of the registration options where you get a callback that contains a kernel (example: https://github.com/castleproject/Windsor/blob/master/docs/inline-dependencies.md#supplying-dynamic-dependencies or https://github.com/castleproject/Windsor/blob/master/docs/lifecycle.md#the-oncreate-method).  You'd want Windsor to track something you resolved from the kernel during the execution of the lambda because it's intimately tied to the component you're registering (and subsequently resolving).  The same creation context applies to the IInitializable interface, other callbacks to get parameter values and, eventually, the invoked constructor.

Now that the documentation is in GitHub I may suggest, via PR, some tweaks to make the above (in hindsight, obvious) observations clear in the docs.  For example, the startable facility is discussed in the lifecycle doc page (https://github.com/castleproject/Windsor/blob/master/docs/lifecycle.md#writing-your-own) as a custom lifecycle concern but it's not entire clear if things resolved during the Start() are also tracked in this manner.  The relevant bit of code is at https://github.com/castleproject/Windsor/blob/master/src/Castle.Windsor/Facilities/Startable/StartableContributor.cs#L63 but, just browsing around the code in GitHub, I'm not sure if model.Lifecycle causes relationships/burdens to be created or not...

Sorry for the long thought bubble.  This has been an interesting 30 minute side project :grinning:

**Comment by IanYates** [comment]
@hikalkan - just saw your reply (came in whilst I was on my side track).

So what you want is something like multiple singleton ICache instances, each distinguished by a key.  

That's effectively what you're trying to achieve with the dictionary and you were relying on 
a) transient ICache registration meaning you'd get a new one each time
b) your dictionary handling whether or not you actually want to invoke Windsor to get a new ICache instance or not
c) never disposing of any of the ICache instances in your dictionary
But Windsor's creation context was getting in the way :)

How about registering your ICache as a transient, as you're already doing, but set it to be externally managed (since that's what you're already trying to do).  Windsor then won't track the created ICache instances and thus they won't get disposed.

Also, is there any time where you do dispose of an ICache instance?  If not, could you also not make it disposable?

**Comment by hikalkan** [comment]
Thank you very much @IanYates for your valuable time spending on that.
That's very unexpected by me. As you said, IInitializable does not solve the problem (I did try it). Windsor has a creation context (Maybe with a CallContext stuff) and if we resolve some object in this context, it makes a relation and disposes it.

**Comment by hikalkan** [comment]
@IanYates thanks. Yes you understood me well :)
What do you mean by "externally managed"? Notice that I don't know names of caches before. So, I create a singleton ICache per name.
I dispose (release) ICache objects when ICacheManager is disposed (So, when Kernel is disposed since ICacheManager is singleton). No problem.

**Comment by IanYates** [comment]
"externally managed" is me misremembering the appropriate term :)

Something like
```
container.Register( Component.For<ISomething>().UsingFactoryMethod(......, managedExternally: true) );
```

The ... represents various overloads available for UsingFactoryMethod.  All involve some kind of Func - one with no parameters, one that takes the kernel, another with the kernel & creationContext and another with even more parameters.  Choose the appropriate one and set the managedExternally boolean true so that Windsor won't track the component for release.

**Comment by hikalkan** [comment]
That's good and maybe the what I'm looking for. Thank you very much :)

**Comment by IanYates** [comment]
No problem - glad I could help (and I enjoyed the exercise)

**Comment by hikalkan** [comment]
Let's see this :)

```C#
Component.For<MyDisposableClass>().UsingFactoryMethod(kernel => kernel.Resolve<MyDisposableClass>(), managedExternally: true),
```

It's obviously not working because of circular dependency. But you understand me. I want that MyDisposableClass can inject dependencies. So, it should be resolved from IOC :(

**Comment by IanYates** [comment]
Not quite :)

You'd need to do something more like

```
Component.For<MyDisposableClass>().UsingFactoryMethod(() => new MyDisposableClass(), managedExternally: true)
```

You're teaching Windsor how to resolve the class manually.

You could use the provided `IKernel` instance to still resolve parameter values required for `MyDisposableClass`'s constructor.  How those dependencies are tracked....  Hmm :D

**Comment by fir3pho3nixx** [comment]
@hikalkan - What is this state of this, can we close?

**Comment by hikalkan** [comment]
Yes we can close. Thanks.
