### ISSUE TITLE
NHibernateIntegration facility

### ISSUE THREAD

**Issue by fsalas** [castleproject/Windsor#101]
Hi, by any chance is the facility broken for castle 3, I'm trying to use it, and keep getting an exception, or the facility is deprecated and I should use another in replacement as the nuget package Castle.Facilities.NHibernate

I'm building some tests with the following code, and getting 

```
System.MissingMethodException : Method not found: 'Void Castle.Core.DependencyModel..ctor(Castle.Core.DependencyType, System.String, System.Type, Boolean)
```

The Stack Trace is:

```
   at Castle.Facilities.NHibernateIntegration.Internal.NHSessionComponentInspector.ProcessModel(IKernel kernel, ComponentModel model)
   at Castle.MicroKernel.ModelBuilder.DefaultComponentModelBuilder.<>c__DisplayClass6.<BuildModel>b__4(IContributeComponentModelConstruction c)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Castle.MicroKernel.ModelBuilder.DefaultComponentModelBuilder.BuildModel(IComponentModelDescriptor[] customContributors)
   at Castle.MicroKernel.Registration.ComponentRegistration`1.Castle.MicroKernel.Registration.IRegistration.Register(IKernelInternal kernel)
   at Castle.MicroKernel.DefaultKernel.Register(IRegistration[] registrations)
   at Castle.Facilities.NHibernateIntegration.NHibernateFacility.RegisterDefaultConfigurationBuilder()
   at Castle.Facilities.NHibernateIntegration.NHibernateFacility.RegisterComponents()
   at Castle.Facilities.NHibernateIntegration.NHibernateFacility.Init()
   at Castle.MicroKernel.Facilities.AbstractFacility.Castle.MicroKernel.IFacility.Init(IKernel kernel, IConfiguration facilityConfig)
   at Castle.MicroKernel.DefaultKernel.AddFacility(String key, IFacility facility)
   at Taxo.Framework.Test.Persistance.NHibernate.NHibernateModuleInitialization.ConfigureNHibernateFacility(IWindsorContainer _ioc) in C:\Proyectos\Sistemas\CatalogLegacy\dev\Framework\Test\Test\Persistance\NHibernate\NHibernateModuleInitialization.cs:line 74
   at Taxo.Framework.Test.Persistance.NHibernate.NHibernateModuleInitialization.Setup() in C:\Proyectos\Sistemas\CatalogLegacy\dev\Framework\Test\Test\Persistance\NHibernate\NHibernateModuleInitialization.cs:line 39
```

Here is my code, I'm initializing the facility from code as is just for tests

```
[SetUpFixture]
public class NHibernateModuleInitialization 
{
    [OneTimeSetUp]
    public void Setup()
    {


        Ioc = new WindsorContainer();
        Ioc.AddFacility<TypedFactoryFacility>();
        Ioc.AddFacility<LoggingFacility>(f => f.LogUsing<NullLogFactory>());
        ConfigureNHibernateFacility(Ioc);

        new Taxo.Framework.Context.Ioc.CastleWindsor.Installers.WindsorInstaller().Install(Ioc, Ioc.Kernel.ConfigurationStore);
        new Taxo.Framework.Persistance.NHibernate.Installers.WindsorInstaller().Install(Ioc, Ioc.Kernel.ConfigurationStore);
        new Taxo.Framework.Test.Persistance.NHibernate.Installers.WindsorInstaller().Install(Ioc, Ioc.Kernel.ConfigurationStore);

        var cfg = Ioc.Resolve<Configuration>();
        new SchemaExport(cfg).Create(false, true);
    }

    [OneTimeTearDown]
    public void TearDown()
    {
        var cfg = Ioc.Resolve<Configuration>();
        new SchemaExport(cfg).Drop(false,true);

        Ioc.Dispose();
    }


    public static IWindsorContainer Ioc { get; private set; }


    //public static ISessionFactory Sessions { get; private set; }

    /// <summary>
    /// Crea la configuracion de la facility de NHibernate, para testing usamos todo en codigo, incluso la conexion a sqlite
    /// en memoria, para el codigo real la configuracion de base de datos hay que sacarla del config
    /// </summary>
    /// <param name="_ioc">Contain</param>
    public void ConfigureNHibernateFacility(IWindsorContainer _ioc)
    {
        var config=new NHibernateFacilityConfigurationBuilder();

        _ioc.Kernel.ConfigurationStore.AddFacilityConfiguration("nhibernate", config.BuildBaseConfiguration());
        _ioc.Kernel.AddFacility("nhibernate", new NHibernateFacility());

        //Me parece que hay un bug en castle que hace que esta no funcione
        //           _ioc.AddFacility<NHibernateFacility>("nhibernate");

    }
}

public class NHibernateFacilityConfigurationBuilder : IConfigurationBuilder
{
    public IConfiguration BuildBaseConfiguration()
    {
        MutableConfiguration facility = new MutableConfiguration("facility");
        facility.Attributes.Add("id", "nhibernate");
        facility.Attributes.Add("isWeb", "false");
        facility.Attributes.Add("defaultFlushMode", "Never");
        facility.Attributes.Add("type", "Castle.Facilities.NHibernateIntegration.NHibernateFacility,Castle.Facilities.NHibernateIntegration");

        //          Podria agregar un configuration builder para usar el fluent ver ejemplo Ana.Persistencia.Implementacion.FluentNHibernateConfigurationBuilder
        //            facility.Attributes.Add("configurationBuilder", "Class,Assembly");

        MutableConfiguration factory = facility.CreateChild("factory");

        factory.Attributes.Add("id", "nhibernate.factory");

        MutableConfiguration settings = factory.CreateChild("settings");

        CreateItem(settings, "connection.provider", "NHibernate.Connection.DriverConnectionProvider");
        CreateItem(settings, "connection.driver_class", "NHibernate.Driver.SQLite20Driver");
        CreateItem(settings, "connection.connection_string", ":memory:;Version=3;New=True;");
        CreateItem(settings, "dialect", "NHibernate.Dialect.SQLiteDialect");

        MutableConfiguration assemblies = factory.CreateChild("assemblies");
        MutableConfiguration assembly = assemblies.CreateChild("assembly");

        assembly.Value = "Taxo.Framework.Test";

        return facility;
    }


    private void CreateItem(MutableConfiguration _config, string _key, string _value)
    {
        var item = _config.CreateChild("item");

        item.Attributes.Add("Key", _key);
        item.Value = _value;
    }
}
```

I googled it a bit and found a report here, with suggestions

https://github.com/castleproject/castle-youtrack-export/blob/master/FACILITIES/FACILITIES-156.xml

and a message in the forums

https://groups.google.com/forum/#!topic/castle-project-devel/JceQKHPLrYs

Thanks in advance

Fernando

**Comment by jonorossi** [comment]
Yes, it won't work with Windsor 3, where are you getting it from because the Castle Project last released the NHibernateIntegration facility in ZIP only format with Windsor?

@kkozmic dropped (b86d0da1ddf4347bcf214220a76c2e78858cf3a8) both the ActiveRecordIntegration and NHibernateIntegration facilities leading up to Windsor 3. I don't know why it didn't make its way into the 3.0 release notes. I assume since we've still got the source code in the repository Krzysztof was going to reinstate it but it didn't happen.

We don't have a maintainer for our facility which is why it has died, however feel free to send a pull request to bring it back to life, otherwise you could try the third party `Castle.Facilities.NHibernate` facility that you found.

**Comment by fsalas** [comment]
Jonorossi, thanks for the answer, I've got it from Nuget, as it is still there,

It is also listed in

https://github.com/castleproject/Windsor/blob/master/docs/facilities.md

so I thought it was a sort of 'official' facility, I can test the pathces on the article and then fill a pull request, but I don't (still) know the castle internals to really know what the changes does other tan avoid the errors.

I can also try the other facility, which is built over the new Transactions facility.

Then the question is, what do you recommend of the two?, As you are a contributor, thats know far more about castle than me, what would you think is better? 

Thanks in advance

**Comment by jonorossi** [comment]
Yep, the documentation has it because it is an official facility however hasn't been maintained for Windsor 3, as I mentioned we didn't officially decide to drop it, it just happened to get dropped in Windsor 3.

So you are using this NuGet package: https://www.nuget.org/packages/Castle.Facilities.NHibernateIntegration/. I don't know who the owners of that package are by looking at their user names, but that isn't maintained by the Castle Project. It seems there are quite a few forks of this facility on GitHub and NuGet.

To be honest, since there isn't anyone contributing to Castle that has any need to maintain the facility unless someone steps up it'll stay in its current state. We are happy to review/merge changes and provide basic assistance via GitHub issues or the mailing list to help someone update it.

It is really your call whether you want to help get the official Castle facility updated and working again or use one of the forks.

**Comment by fsalas** [comment]
Jonhaton:

Thanks again for your comments. Even after being able to make it work with one of the third party facilities, I would be more confident if I can make the official one to work. 
I would like to give it a shot to upgrade it to work with castle 3
What would be the link to the official sources of it then?,
Based on your knowledge about the differences between castle 2 and 3, do you think it would need just some adjustments or major change?

Thanks in advance

Fernando

**Comment by jonorossi** [comment]
@fsalas the code lives in the Windsor repository under `src/Castle.Facilities.NHibernateIntegration{.Tests}`. There were quite a lot of breaking changes between Windsor 2 and 3, unfortunately I don't know how many affect this facility, but since others were able to get it working it is definitely do able.

**Comment by jonorossi** [comment]
Closing this in lieu of #205.
