### ISSUE TITLE
Avoid Too many constructor parameter ?

### ISSUE THREAD

**Issue by balamurugansanthanaraj** [castleproject/Windsor#113]
How do I avoid too many constrcutor parameter ? In my case I have 14 parameter, it really look very bad. Do u have any idea ?

**Comment by MiguelAlho** [comment]
There are a couple of things worth considering in this case. First, a class that takes 14 parameters is probably very big, especially if a good part of those parameters are services. If that's the case, you'll probably only have methods using some of the services at any given moment, and never all of them at the same time. As such, you may want to review the class and see if you can break it down into smaller  classes, with more cohesive methods.These new classes should have less methods and because of that less inputs.

Another thing to consider is if the constructor parameters are data or state information. Can they be grouped into a class, and use that class as an input?

**Comment by s-tarasov** [comment]
It's not Windsor problem

**Comment by balamurugansanthanaraj** [comment]
Yes.. I agree that it is not a Windsor problem. 
Does Windsor have any other options to handle this problem ?

**Comment by fir3pho3nixx** [comment]
No you have to use more objects to avoid constructor bloat. It is really up to you and how you structure your code.
