### ISSUE TITLE
TypedFactory Disposes Before Component That Depends on it

### ISSUE THREAD

**Issue by pnquest** [castleproject/Windsor#114]
If a typed factory is a dependency of a disposable component, it is already disposed by the time dispose is called on that component. 

If I directly implement the factory myself rather than using the typed factory, everything behaves as I would expect.

[This SO Question also details the issue](http://stackoverflow.com/questions/34361165/typedfactory-disposes-before-component-using-it-as-a-dependency)

I have attached a test solution below that shows this behavior (although it is not actually useful itself).

[WindsorTypedFactoryDisposalTest.zip](https://github.com/castleproject/Windsor/files/67637/WindsorTypedFactoryDisposalTest.zip)

**Comment by jnm2** [comment]
I am having the same problem. If I use a factory to construct an `IDisposable`, *I* am the one responsible to put it in a using statement or call Dispose. That is kind of the whole point of injecting a `Func<DbContext>`- so that I have absolute control of creation and disposal of every DbContext. I need that control.

**Comment by jnm2** [comment]
Here is another repro, very tiny and to the point: [Test Castle Windsor dispose out of order.zip
](https://raw.githubusercontent.com/jnm2/misc-codesamples/master/Bug%20reports/Castle%20Windsor/Test%20Castle%20Windsor%20dispose%20out%20of%20order.zip)

This is causing our application to crash in production. Is there a workaround?

**Comment by pnquest** [comment]
@jnm2 I ended up not using the typed factory feature at all and ended up creating my own full factory class instead. When you create your own factory, and wire it up along with everything else it will behave as expected.

**Comment by jnm2** [comment]
@pnquest That would be unnecessarily disruptive if there's *anything* else I can do. I'm using delegate factories and the delegate factories are what is keeping track of releasing the dependencies of the components they provide.

@hammett Any idea what the ETA might be?

**Comment by jnm2** [comment]
I think I found a workaround for the time being- replace `dependencyFactory.Invoke()` with `TypedFactoryWorkaround(dependencyFactory)`:

```c#
private T TypedFactoryWorkaround<T>(Func<T> typedFactory)
{
    try
    {
        return typedFactory.Invoke();
    }
    catch (ObjectDisposedException)
    {
        // Workaround for https://github.com/castleproject/Windsor/issues/114
        Dispose();
        throw new OperationCanceledException();
    }
}
```

**Comment by pnquest** [comment]
@jnm2 That works fine if you are looking to just gracefully fail, in my case there was still data flowing through that needed to be handled before shutdown could be finalized. In that situation your workaround will not help.

**Comment by jnm2** [comment]
@pnquest Exactly.

**Comment by jnm2** [comment]
I'm still running into this big time. @hammett Did you make any progress on this?

**Comment by hammett** [comment]
I'm tracking this at https://github.com/castleproject/Windsor/pull/61 
I believe it's the same issue, correct?

**Comment by jnm2** [comment]
@hammett I wasn't positive, it's been so long. Is there anything I can do to help crack this one?

**Comment by hammett** [comment]
Aside from debugging it and fixing it yourself, no. This is new code to me as well since I haven't written that part of Windsor

**Comment by jnm2** [comment]
@hammett I'll be able to try my hand at it in two weeks.

**Comment by fir3pho3nixx** [comment]
We are thinking of deprecating this facility, please join the discussion at https://github.com/castleproject/Windsor/issues/339

**Comment by jnm2** [comment]
@fir3pho3nixx Looks like both of you are thinking of actually keeping this facility which is good, because otherwise I'd have to cut my losses now. 😄

**Comment by jonorossi** [comment]
Yep, the Typed Factory facility is staying as is UsingFactoryMethod, the Factory Support facility is the one we are looking at deprecating. Reopening.

**Comment by fir3pho3nixx** [comment]
Whoops wrong factory!

**Comment by jnm2** [comment]
@fir3pho3nixx @jonorossi I want to pick your brains on this issue. As a practical matter, things have come to a head with this issue and I've been looking at fixing it.

Simple failing test: https://github.com/castleproject/Windsor/compare/master...jnm2:fix_typed_factory_out_of_order_dispose

Reason: TypedFactoryInterceptor must not be disposed until all handlers which use typed factories are disposed, because the handlers may need to invoke their typed factory dependencies in order to be disposed.

The problem is, `DefaultKernel.Dispose` contradicts this necessity by doing things in this order:

 1. Calls `DisposeComponentsInstancesWithinTracker` which disposes `TypedFactoryInterceptor`
 2. Calls `DisposeHandlers` which disposes a service whose Dispose method invokes a typed factory

I've looked and tried things for a few hours but the complexity of the internals is daunting. What approach would you take to fix this?

https://github.com/castleproject/Windsor/blob/8e139da134c0640dceefb4a8a043af1958e60927/src/Castle.Windsor/MicroKernel/DefaultKernel.cs#L233-L245

**Comment by jnm2** [comment]
Do we need to invent a way to postpone an interceptor's disposal until after the handlers have been disposed?

**Comment by jnm2** [comment]
Or maybe we need a way to make sure the handler for `TypedFactoryInterceptor`, created by [`InterceptorReference.IReference<IInterceptor>.Resolve`](https://github.com/castleproject/Windsor/blob/8e139da134c0640dceefb4a8a043af1958e60927/src/Castle.Windsor/Core/InterceptorReference.cs#L158), ends up in the `DisposeHandlers()` list instead of the `DisposeComponentsInstancesWithinTracker()` list.

That way it could be topologically sorted, so long as the dependencies are reflected properly between it and the handlers that use typed factories.

**Comment by jnm2** [comment]
The `TypedFactoryInterceptor` already does end up in the `DisposeHandlers`, and it is topologically sorted properly. So we just need a way to keep it from being disposed by `DisposeComponentsInstancesWithinTracker`, which just releases the container's lifetime policy.

**Comment by jnm2** [comment]
Wait... is it really this easy? I thought I had already tried switching the order of the `DisposeHandlers` and `DisposeComponentsInstancesWithinTracker` calls, but now it's working!

`DisposeComponentsInstancesWithinTracker` makes sense as a backstop for anything `DisposeHandlers` didn't clean up organically via reference counting, and no tests tested to fail, so I'm satisfied with this...

**Comment by jnm2** [comment]
https://github.com/castleproject/Windsor/pull/344

**Comment by jonorossi** [comment]
@jnm2 great work working through that, now that we've got a unit test that defect is now squished forever.
