### ISSUE TITLE
Are Child Containers still relevant? Is there any docs?

### ISSUE THREAD

**Issue by zldrq** [castleproject/Windsor#115]
Looks like they are alive, but I have no luck trying to find anything about their behavior.

**Comment by jonorossi** [comment]
Child containers aren't really documented because it is recommended to use [han­dler selec­tors](https://github.com/castleproject/Windsor/blob/master/docs/handler-selectors.md) and [sub dependency resolvers](https://github.com/castleproject/Windsor/blob/master/docs/resolvers.md) in preference to child containers. There are still edge cases that don't work as people expect with child containers.

Krzysztof wrote a blog series a few years back:
* http://kozmic.net/2010/06/01/castle-windsor-and-child-containers/
* http://kozmic.net/2010/06/02/castle-windsor-and-child-containers-reloaded/
* http://kozmic.net/2010/06/03/castle-windsor-and-child-containers-empire-strikes-back/

Most of the Windsor docs were written during the time when there were some big defects with child containers so I suspect that is why no docs were written at that time.

**Comment by fir3pho3nixx** [comment]
Lifecycles are incredibly hard to propagate between parent child containers. This is an example of where I tried to submit a PR fixing transient disposals with parent registrations via child container resolution: https://github.com/castleproject/Windsor/issues/324. 

The question I have is why is this abstraction necessary? 

The Microkernel has so many ways of solving these problems(handler selectors and sub resolvers), what problem are you trying to solve by doing this?

Will add this to the V5 Windsor discussion which was looking more about obsolescence but now feels like we need to delete something that should have never existed.

**Comment by fir3pho3nixx** [comment]
Please join us over there to voice your thoughts.
