### ISSUE TITLE
Typed factory should not track or dispose the objects it creates

### ISSUE THREAD

**Issue by jnm2** [castleproject/Windsor#139]
If  an object is created by **Castle Windsor** calling the typed factory's resolve/create method, then I agree that Castle Windsor should be the one to release/dispose.

If an object is created by **me** calling the typed factory's resolve/create method, then I should be the one to release/dispose.

In other words, the returned object's lifespan should not be tied to the factory but to whatever **caused** the call to the factory. That could be me manually (in which case I manually manage the lifespan), or it could be Castle Windsor resolving a component (in which case the lifespan should be tied to the component that needs the object, not to the factory itself). In neither case should the typed factory itself be tracking the objects it creates.

If I use a factory to construct an `IDisposable`, *I* am the one responsible to put it in a `using` statement (if it's a local) or call `Dispose` (if it's a field). It's the expected pattern in .NET with any `IDisposable`-returning creation method.

In my case, that is **kind of the whole point of injecting a `Func<DbContext>`**- so that I have absolute control of creation and disposal of every DbContext. I need that control.

The only reason I'm not newing up the DbContext myself in the `using` block is that the DbContext has a dependency, but I need the same semantics:

```c#
using (var db = new MyDbContext(thingsToInject))
{
	var query1 = await db.Thing1();
	var query2 = await db.Thing2();
	...
	await db.Command();
}
```

Should have the same disposal semantics, but doesn't:

```c#
using (var db = dbContextFactory.Invoke()) // Use Castle Windsor to handle DI
{
	var query1 = await db.Thing1();
	// Problem happens when Castle Windsor (rightfully) disposes dbContextFactory because the viewmodel is closed
	// db gets disposed too early! I need it to last until the end of the using block! (duh?)
	var query2 = await db.Thing2();
	...
	await db.Command();
}
```

I need at least an option to disable tracking objects instantiated by **me** from typed factories, but I also think it's a more preferable idiom to not track them and that tracking object returned from manual calls should be disabled completely or at least disabled by default.

**Comment by hammett** [comment]
The issue of lifetime is more intricate than that. If the only disposable thing is the root object, and its contract explicitly expose that fact (IDisposable), than your assertion is one that is hard to disagree with. However, the graph constructed may not have a disposable root, or it may not advertise that on its contracts, or inner objects are the ones disposable. 

By convention, since the container is the one entity that actually knows all that, it's the only that can dispose the whole graph correctly (also respecting the lifetime of individual components used in the graph transitively). 

I'm not that familiar with the typed factories, though, so I may be missing something or their impl might not be using the correct convention.

**Comment by jnm2** [comment]
Not sure I follow. Whether or not the graph has a disposable root, I still want inner objects that are resolved/created by factories by Castle Windsor in order to inject into the root to be released/disposed when the root is released. Not because they are tied to the factory bu because they are tied to the root as dependencies. And I still do not want objects that I manually resolve/create by a factory to be released/disposed when the root object is released.

**Comment by hammett** [comment]
That's the thing with lifetime/ownership. Everyone has their own opinions, and there's no way to accommodate all permutations of possibilities. 

I've worked/written extensively on the topic.

https://blogs.msdn.microsoft.com/hammett/2008/10/16/dependencies-ownership-and-lifetime/
http://hammett.castleproject.org/index.php/2009/01/mef-and-lifetime/

Unless there's a bug, I'm not inclined to change the convention that windsor applies.

**Comment by jnm2** [comment]
The bug is that I don't have a way to make this situation work.

Here's the difference: instead of tracking an object inside the generated `Func<T>.Invoke`, track it like any other component: only when it is used as a dependency by some other component. That way I can still call Invoke and get an IDisposable to use and dispose without causing tracking, and Castle Windsor can continue tracking in every case it needs to by default.

**Comment by jnm2** [comment]
I need the same generated injected `Func<DbContext>` to 1) hand me non-tracked DbContexts when I manually call `Invoke` and 2) supply Castle Windsor with DbContexts to inject into services that take `DbContext` rather than `Func<DbContext>`. Same story with `SqlConnection`.

**Comment by jberezanski** [comment]
Out of the two flavors of typed factories, [the interface-based ones](https://github.com/castleproject/Windsor/blob/master/docs/typed-factory-facility-interface-based.md) provide more control: the factory has methods both to construct and destroy objects. It is slightly less convenient to use, because it requires `try...finally` instead of a simple `using` block:

````
var db = dbContextFactory.Create();
try
{
    ...
}
finally
{
    dbContextFactory.Release(db);
}
````

Indeed, typed factories abstract away both creation and destruction concepts, so I'd say when using typed factories one should entirely forget about IDisposable - it is a private implementation detail of the specific type being constructed. If the object should be Dispose()d, the factory will do it once the object is returned to it via Release(). (this mirrors the behavior of Resolve/Release of WindsorContainer itself)

The assumption with typed factories is that the lifetime of the factory should encompass the lifetimes of all objects created by it (which is only sensible, since all created objects should be returned to the factory). The release of all not-yet-released objects upon the destruction of the factory is a useful safety net, mitigating memory leaks due to programming errors (forgetting to return a component to the factory). The issue with premature disposal of the factory in certain nontrivial scenarios is a real bug in Windsor, however - but you have already [seen that](https://github.com/castleproject/Windsor/pull/61).

As for your specific scenario - I'm not sure what your code looks like, but if the following sequence of events is correct:
- your code operating on the DB is contained in a ViewModel class, in a method that gets triggered upon some UI action,
- the DB code starts executing, reaches an async point and control returns to the UI,
- the view is closed, the ViewModel is destroyed while the DB code is still running,
- the typed factory was constructed as a dependency of the ViewModel and, as such, is destroyed together with it, disposing the DbContext,
- upon resuming from an async point, the DB code crashes because the DbContext has been disposed,
then I'd say the error is in the design, as the ViewModel should not have been allowed to be destroyed while its code is still running. (A similar class of errors tends to appear in Windows Forms code when using timers or other notification mechanisms.)
I suggest one of the following approaches to the problem:
1) (the more elegant approach) refactor the DB code out of the ViewModel and into a separate component (in the logical Model layer), whose lifetime will be longer than the lifetime of the ViewModel,
2) (the more quick hack-smelling approach) use an interface-based typed factory, register it as Singleton and trigger its creation (Resolve it) at application startup, so that its lifetime will not be coupled to that of the ViewModel object.

**Comment by jnm2** [comment]
1) I simplified- the database code is not actually in the viewmodel but is in a service which injected into the viewmodel and is disposed along with the viewmodel. Same problem, one step further removed.

2) I was hoping to avoid the quick hack smelling kind of thing with a best-of-breed container.

**Comment by ivan-danilov** [comment]
It is not a violation of RRR. Release method of the factory not necessary tied to actual release. You just let the container know that this factory does not need this object anymore.

With factory-constructed objects you have to rely on this method rather than on standard Dispose. You don't track/call Dispose on each and every of your dependency, don't you? You must not actually, because some of them might be singletons. But if you call Dispose on something created with factory - you must somehow let container know that. And that is the purpose of Release method.

**Comment by jnm2** [comment]
The problem is I never get a *chance* to release because the factory gets disposed too soon. If *I* resolve, *I* should release. If Castle Windsor resolves, Castle Windsor should release.

Since we aren't using `try...finally` and the interface method, executing `Func<DbContext>.Invoke` *is* the resolve and disposing the DbContext is all the release there can be and all there needs be. I know what to do with an IDisposable. The pattern is everywhere in .NET. You never ever have an IDisposable local without putting it in a `using` statement. Since the delegate factory inherently has no `Release` method, and `Dispose` is guaranteed to be called because I'm following .NET coding guidelines, there is literally no reason for the delegate factory to be tracking anything.

The failsafe aspect is causing idiomatic issues and is not worth it. There's no failsafe for most IDisposables. That's fine. If I miss one, I pick it up in memory profiling. Same as event handlers. No big deal. (Yes, there's finalize but if you're relying on finalization to dispose your IDisposables you have utterly failed.)

**Comment by ivan-danilov** [comment]
@jnm2 you're not correct here. Suppose your context was registered in Windsor with PerWebRequest lifestyle. In this case your class that uses the context just doesn't have enough information to decide whether that DbContext should be disposed or not. It doesn't know whether it is the only one depending on this DbContext during handling of the web request. Only the container has this knowledge. Hence, with container-registered classes you have to forget about disposing IDisposables that were handed to you from Windsor. Container must take care of them, and container only.

Your responsibility is just point the container that your class (that is user of the factory) does not need that constructed object anymore. And container's responsibility would be to decide what to do with it afterwards. I guess to dispose if it is Transitive, to leave as it is if it is Singleton or more complex cases with other policies.

**Comment by jnm2** [comment]
I'm willing to be convinced, but I don't think so. Here's why: in that scenario, I would be taking a `DbContext` dependency, not a `Func<DbContext>` dependency. If you were doing DI manually this is exactly what the plumbing code would do. In any case, `Func<DbContext>` implies that I'm going to call the function more than once in some cases and receive more than one `DbContext`. If I have more than one unit of work, I definitely do not want to be reusing DbContext instances. If I only ever need one `DbContext`, I take a `DbContext` dependency instead of a `Func<DbContext>` dependency.

Since `Func<DbContext>` implies that I'm calling more than once with the expectation of receiving a new instance each time, no lifestyle but transient makes sense and the return value of `Func<DbContext>` fits the `using` statement semantics perfectly.

In fact, some services I'm using take a `Func<DbContext>` when they could take a `DbContext` simply as a way of saying "You don't have to worry about lifestyle from the outside; I'll manage it myself."

Now, since Castle Windsor knows 1) that my `Func<DbContext>` is configured to return transients and 2) there is no release method, it should realize at this point that it should not be tracking anything.

**Comment by ivan-danilov** [comment]
Why do you think that having `Func<T>` forces container to return new instance each time? It is not the case in fact.

Also there're different reasons beside my example, that @hammett pointed out for you before. In particular your DbContext has some dependencies that container satisfies. As calling Dispose on DbContext does not notify Windsor - these dependencies are now flying somewhere in the memory.

I'd say that Windsor's strategy is totally correct here, and should remain as it is.

**Comment by jnm2** [comment]
I don't think that `Func<T>` forces the container to do anything. What I do think is that semantically, Func<T> represents the ability to obtain multiple `T`s and also control when in time the `T`s are created. If `Func<T>` is not used for multiple instances or for controlling the lifestyle, you should just use `T` because it is semantically more appropriate.

> In particular your DbContext has some dependencies that container satisfies. As calling Dispose on DbContext does not notify Windsor - these dependencies are now flying somewhere in the memory.

Now that is a very good point which I didn't catch earlier, which does seriously challenge my position. You are right about this. I actually do need to release DbContexts, so I'm forced to use interface factories or wait for the delegate factory to be disposed and hope that isn't too long.

**Comment by jnm2** [comment]
So my solution will be to either prevent the view model from being disposed until all related async activities are finished, or to find some way to get free of the lifespan of the viewmodel without leaving the data service hanging forever. Can it release itself? That sounds hacky to me.

**Comment by jnm2** [comment]
So my solution will be, depending on the operation, either 1) to prevent the view model from being disposed until all related async activities are finished, or 2) get free of the lifespan of the viewmodel by using a singleton data service, or 3) cancel the async operations and recheck the cancellation token after every await.

**Comment by ivan-danilov** [comment]
@jnm2 
I guess someone resolved your VM somehow (either as a dependency or via Resolve method). So I think it is their responsibility to track when it should be released (and all of its graph of dependencies including the factory as well). I usually have a chain of factories, so opening VM often looks like this:

    var vm = factory.CreateSomeVM();
    vm.Closed += factory.Release(vm);
    ViewService.Show(vm);

Obviously your approach may differ, but general point is that instead of releasing on `Closed` event you might have something like `Task` property representing unfinished processes, on which you can schedule a continuation releasing VM.

**Comment by IanYates** [comment]
This seems pretty much concluded as a discussion, but it was a good read.  I use interface-based typed factories for the very reason that was ultimately mentioned

```
In particular your DbContext has some dependencies that container satisfies. As calling Dispose on DbContext does not notify Windsor - these dependencies are now flying somewhere in the memory.
```

It also means that if my DbContext was a singleton instead of transient, it could potentially be kept around rather than new'd and disposed each time.

One other thing typed factories offer is the ability to accept parameters as part of the `factory.create(..)` method and have them flow through to the eventually created component.  I don't use it often but it's been handy when required.

Lifetime then isn't managed by IDisposable, but that's OK because the factory interface is your code and it's not hidden - it's actually part of the contract to get a new widget constructed (Windor's automatic implementation of the interface is what makes this all very elegant IMHO).
