### ISSUE TITLE
Component For an interface not a class

### ISSUE THREAD

**Issue by mwpowellhtx** [castleproject/Windsor#153]
Example after example that I read illustrates ``Component.For<ISomeInterface>.ImplementedBy<SomeImplementation>()``, however, *Castle.Windsor* version 3.3 wants a **class**.

Was this an oversight? How exactly do you register a concrete type (service, "component", or what have you) "as" one or more interfaces?

Thank you...

**Comment by mwpowellhtx** [comment]
Ah, okay, so this has to do with C# generics:

```C#
public static void EnableRuntimeMeasurements<TService, IService>(this IWindsorContainer container)
    where IService : IRuntimeInstrumentationDiscoveryService
    where TService : class, IService
{
    container.Register(
        // Is an error, since IService could be a struct and not a class (i.e. reference type)
        Component.For<IService>().ImplementedBy<TService>()
    );
}
```

However, this seems to work, which is probably okay for what I want to accomplish:

```C#
        Component.For<IRuntimeInstrumentationDiscoveryService>().ImplementedBy<TService>()
```

**Comment by jonorossi** [comment]
@mwpowellhtx if I understand the problem you were encountering it is because Windsor's `Component.For<TService>` requires `TService` to be a reference type and so defines the generic constraint `where T : class`. In C# this doesn't mean it has to be a class, but just a reference type (class or interface, since struct don't have a v-table so can't have an interface).

Just change your first generic constraint to `where IService : class, IRuntimeInstrumentationDiscoveryService` and you won't get a compiler error calling `For<>`.

**Comment by mwpowellhtx** [comment]
@jonorossi Really? I did not know that. I figured ``class`` meant *concrete class*, not *reference type*. As contrasted with the ``new()`` constraint, at any rate. I'll look into that. Thanks for clarifying.

**Comment by mwpowellhtx** [comment]
@jonorossi That works, thanks for pointing that out.
