### ISSUE TITLE
.NET Core Support: Port code with alternatives in .NET Core

### ISSUE THREAD

**Issue by alinapopa** [castleproject/Windsor#239]
- [x] Use Type.GetTypeInfo() to replace the old Type methods
    - [x] Replace [MethodImpl(MethodImplOptions.Synchronized)] with locks
    - [x] System.Web and System.Web UI: PerWebRequestLifestyle is for use with ASP.NET. Remove it on .NET Standard.
    - [x] remove the use of ICloneable 
    - [x] Replace System.Array methods with ones that exist on Core
    - [x] Get alternatives for Assembly.GetCallingAssembly: replace with a method that requires the assembly to be passed in
    - [x] Replace Delegate.CreateDelegate with MethodInfo.CreateDelegate
    - [x] Use AssemblyLoadContext for dynamic loading of assemblies
    - [x] Windows perf counters: Consider replacing with Diagnostic.Tracing.EventCounter (https://github.com/dotnet/corefx/issues/3906 ) or remove.  

Part of #145

**Comment by fir3pho3nixx** [comment]
We are removing the `PerWebRequestLifestyle` in this task list. This poses an interesting conundrum for supporting aspnetcore.  I have been working on a new lifestyle manager in [fluentwindsor](https://github.com/cryosharp/fluentwindsor/tree/fluentwindsor-next-lifestyles/src/FluentWindsor/Lifetime) but it is not finished yet. @kikalkan has also written an adapter for this but my personal preference would a first class api not a proxy.

**Comment by jonorossi** [comment]
I think we should just conditionally compile out anything `System.Web` for now, that'll get us moving forward and a new one can be added/replace it when things stabilise.

**Comment by jonorossi** [comment]
I think the same with performance counters, conditionally compile use of Windows Performance Counters out until someone contributes a well tested implementation.

A mistake I suspect I made with managing .NET Core support for Castle Core is not just cutting features in the first release and ported them across later, we can't be breaking anyone since no one is using Windsor on .NET Core getting the core shipped and changes can filter through with new releases. The Castle Project has always sucked at actually making releases, more and more frequent isn't a bad thing.

**Comment by fir3pho3nixx** [comment]
@alinapopa - are we still missing something here?

**Comment by alinapopa** [comment]
This is completed.
