### ISSUE TITLE
APTCA consistency

### ISSUE THREAD

**Issue by hammett** [castleproject/Windsor#300]
Looks like Windsor has Aptca enabled but the new version of Castle.Core doesn't which leads to some "interesting" situations. What's our aptca policy, and shouldnt they be consistent across projects? And how does .net standard/core fit in the picture?

Thanks

https://msdn.microsoft.com/en-us/library/ms345097(v=sql.105).aspx

**Comment by jonorossi** [comment]
#248 has a bunch of info I wrote after I reviewed one of the pull requests for the new build tooling where the attribute was removed. I wrongly concluded that it wasn't defined by default in Castle.Core v3.3.3 and prior, and Windsor v3.4.0 and prior, based on seeing this without anything setting the property to true:

```
<AllowPartiallyTrustedCallers Condition="'$(AllowPartiallyTrustedCallers)' == ''">false</AllowPartiallyTrustedCallers>
```
(Castle.Core had the same code: https://github.com/castleproject/Core/blob/v3.3.3/buildscripts/Castle.Common.Targets#L115)

When we moved Castle.Core to support .NET Core (v4.0.0) the attribute got wrapped in an optional `FEATURE_APTCA` conditional (https://github.com/castleproject/Core/commit/55e152f49fc564581114fc0fa5908790c1bbc80d) in `CommonAssemblyInfo.cs` (based off what the build scripts did). Looking at this again now the APTCA used to get defined because it was in one of the `SecurityAssemblyInfo.cs` files, but only for Castle.Core not the other logging assemblies. Windsor was the same, it was disabled in the build scripts but had a `SecurityAssemblyInfo.cs` file too (https://github.com/castleproject/Windsor/blob/v3.4.0/src/Castle.Windsor/SecurityAssemblyInfo.cs).

Looks like I stuffed that up. Windsor 3.4.0 doesn't support Castle.Core 4.0.0/4.1.0 as specified in the NuGet dependencies, so good pick up however you found it.

We can either leave it undefined, or add it back. Adding it back won't break Windsor because we can just make Windsor 4.0.0 (unreleased) require Castle.Core 4.2.0 (unreleased); and the current dependencies don't let you use Core 4.x with Windsor 3.4.0.

> And how does .net standard/core fit in the picture?

.NET Standard is pretty much just like Portable Class Libraries, they don't specify a runtime just a required BCL API, however .NET Core does not have a sandboxing security model and ignores all security attributes. This issue (https://github.com/dotnet/standard/issues/312) has some good info from the horse's mouth, especially "I'd also just add the obligatory reminder that security transparency is no longer supported as a security boundary and Microsoft does not recommend running untrusted code". This is definitely a consistent message from Microsoft over the last few years, OS process isolation is the only decent security boundary.

Windsor 4.0 drops .NET 3.5 support so we no longer have to deal with the old .NET 1.x/2.x CAS security model (just checked, there are no LinkDemands specified) which means `[SecurityRules(SecurityRuleSet.Level2)]` is also unnecessary (always was) as it is the default for .NET 4.x, and we never actually audited our code under the CAS model so it likely had holes.

Just to summarise things for everyone, under .NET 4.x:
- Fully trusted assemblies are SecurityCritical by default (to prevent SecurityTransparent code calling into them)
- Partially trusted assemblies are SecurityTransparent
- SecurityTransparent assemblies cannot call into SecurityCritical assemblies
- Applying APTCA to your fully trusted assembly removes the automatic treatment as SecurityCritical, and marks it SecurityTransparent, the assembly then must mark types and methods with granular SecuritySafeCritical and SecurityCritical attributes where required, SSC for exposed methods, SC for internal methods used by SSC methods

(https://msdn.microsoft.com/en-us/magazine/ee336023.aspx is a good resource)

Looking at the Windsor codebase I was surprised just how few methods and types are marked SecuritySafeCritical and SecurityCritical, I suspect there are a bunch of code paths that don't work under partial trust. If we want to add APTCA we should probably run SecAnnotate and at least have a review of its recommendations.

**Comment by hammett** [comment]
Jono, thanks for being thorough on the reply. Considering .net core as the future, and whole mess of security store in .net is being sunset, I'd vote to remove aptca going forward. 

Regarding how I found it, I indeed had windsor 3.3.0 using Core 4.0.0, nuget didn't complain. The work around was to match both (3.3.0)

**Comment by jonorossi** [comment]
@hammett that is what I was thinking, I haven't heard of anyone running partial trust for years, shared hosting has really faded away, and the old versions are still available. Since APTCA is no longer there, we can close this issue.

> I indeed had windsor 3.3.0 using Core 4.0.0, nuget didn't complain

Ah yes, Windsor 3.3.0 allowed Core 3.3.0+, one of the changes that went into Windsor 3.4.0.

**Comment by fir3pho3nixx** [comment]
Just asking but should we create a minor release fixing the package references? Would help anyone from rediscovering this issue.

**Comment by jonorossi** [comment]
> Just asking but should we create a minor release fixing the package references? Would help anyone from rediscovering this issue.

@fir3pho3nixx when you say minor do you mean releasing 3.3.1? We could but then the same argument could be said for 3.2, and further back. Once we've got a version of Windsor released supporting Castle Core 4.x new projects are likely to be using the new version. I thought NuGet version resolution followed SemVer anyway, so I still don't understand why it assumes ">= 3.3.0" means there are not breaking changes in what SemVer calls a major/breaking version. If we do get more reports of this then we can definitely look at it.
