### ISSUE TITLE
registering class with params constructor: DependsOn() or UsingFactoryMethod()?

### ISSUE THREAD

**Issue by lazaro92** [castleproject/Windsor#303]
I'm looking to register a component in a container and I see that exists two methods:

Method 1:

```
container.Register(
    Component.For<IMongoClient>().ImplementedBy<MongoClient>()
             .DependsOn(Dependency.OnValue("connectionString", "mongodb://host:27017,host2:27017/?replicaSet=rs0"))
    );
```

Method 2:

```
container.Register(Component.For<IMongoClient>()
            .UsingFactoryMethod(
                () => new MongoClient("mongodb://host:27017,host2:27017/?replicaSet=rs0"))
            .LifeStyle.PerWebRequest);
```

I have been searching on Internet but I didn't found nothing. Are the two methods equal? Which is better?

**Comment by mario-d-s** [comment]
`DependsOn` is a configuration method with which you can satisfy a **single dependency** (constructor parameter or property value) of `MongoClient`. Any other dependencies will be satisfied automatically by the container when you resolve `IMongoClient`.

With `UsingFactoryMethod`, you take full responsibility of constructing the component that implements the `IMongoClient` service. Usually, you go with that approach when you need to provide the service implementation dynamically, e.g. when it is not always `MongoClient`.

If `connectionString` is the only dependency, both approaches in this case essentially work the same, but they are two entirely different setups.

Try adding another dependency to `MongoClient` and see what happens. Your second version will no longer compile, and in order to fix it you will likely call `kernel.Resolve`. in your factory method. That is what Windsor can do automatically for you as long as you register the required dependencies with the container.

I'd strongly suggest you stick with your first snippet. It is more robust against changes.

**Comment by jonorossi** [comment]
Ignoring the different lifetimes (singleton in the first one vs per-web request in the second) they are obviously both similar in what they provide in this example but are implemented quite differently.

The first option uses the built-in Windsor creation functionality and Windsor will inject any required dependencies including `connectionString` which you have provided with `DependsOn`, it'll then manage the created component until its destruction at the end of its lifetime.

The second option is using `UsingFactoryMethod` (with `managedExternally = false`) which sets up `FactoryMethodActivator` which is a custom `IComponentActivator` obviously designed to run your creation delegate rather than leaving Windsor to new up the object and pick a constructor to call. If `managedExternally=false` the component will still be tracked for its lifetime and decommission steps will be taken (e.g. to call Dispose if necessary).

I'm going to assume `MongoClient` is an external class inside an third party dependency, in that case using the factory works well because your code will fail to compile if your third party dependency's constructor changes, and it also saves Windsor having to do the work to set up this component, however if you want to start injecting other components into `MongoClient` like logging or something else it might be a good idea to get Windsor to create those dependencies for you.
