### ISSUE TITLE
JsonInterpreter

### ISSUE THREAD

**Issue by ricardoborges** [castleproject/Windsor#367]
I found this thread from the old dev mailing list: https://groups.google.com/forum/#!topic/castle-project-devel/YMMtmr5sZr4

It seems that patch wasn't applied, and Windsor still doesn't have some kind of Json config loader, right?

I'm trying to put at the same place the configurations values for angularjs DI and my castle windsor backend.

**Comment by jonorossi** [comment]
> I'm trying to put at the same place the configurations values for angularjs DI and my castle windsor backend.

This sounds like a bad idea, why would you want to mix server side and client side logic/functionality together?

Correct, Windsor does not have a JSON configuration option just XML, however the direction in recent years has been for everything to be done in C# because the compiler provides a lot of assistance during refactoring and is cleaner. We haven't deprecated XML configuration, but have considered it. What is your use case for wanting external configuration like this?

**Comment by ricardoborges** [comment]
I use XML interpreter only for configuration values, everything else in C#. The story is an integration with Redmine API, that I need to handle a lot of id numbers for the custom columns. That magic numbers I need refer in both server and client side. 

Thank you for the advice, maybe you right! Today, I got that values with a xhr to the server. But, I'm not happy with this approach.

**Comment by fir3pho3nixx** [comment]
I agree with @jonorossi, I am closing this issue. Windsor has moved on from this paradigm. 

Please let me know if you feel different.
