### ISSUE TITLE
Checking for existence of resolver

### ISSUE THREAD

**Issue by eben-roux** [castleproject/Windsor#372]
It would be handy to be able to check whether a specific resolver has been registered, e.g. the `CollectionResolver`.

I need to have the `CollectionResolver` registered but I do not necessarily want to burden the users of my component to do so.  To this end I register it myself.  However, if it is already registered it is not necessary to do so again but I cannot see a way of checking whether it is registered already.

No exception is thrown when registering the same resolver multiple times so it probably isn't a train smash.  I'm assuming the first eligible resolver would be used.

I'd like to add such a check here:

https://github.com/Shuttle/Shuttle.Core.Castle/blob/802ee02fe656b960b87a2fdbdf5587a1e9202dbe/Shuttle.Core.Castle/WindsorComponentContainer.cs#L20

**Comment by fir3pho3nixx** [comment]
You could try this:

```csharp
public static class IDependencyResolverExtensions
{
	public static bool HasResolver<T>(this IWindsorContainer container) where T : ISubDependencyResolver
	{
		var resolver = container.Kernel.Resolver;
		var fieldInfo = resolver.GetType().GetField("subResolvers", BindingFlags.NonPublic |BindingFlags.Instance);
		var subResolvers = (IList<ISubDependencyResolver>)fieldInfo.GetValue(resolver);
		return subResolvers.OfType<T>().Any();
	}
}

```

Here is the unit test:

```csharp
[TestFixture]
public class IDependencyResolverExtensionsTestCase
{
	[Test]
	public void CheckResolver()
	{
		var container = new WindsorContainer();
		container.Kernel.Resolver.AddSubResolver(new CollectionResolver(container.Kernel));

		Assert.That(container.HasResolver<CollectionResolver>(), Is.True);
	}
}
```

**Comment by eben-roux** [comment]
Thanks Gavin,

I did notice the field but perhaps a public method would be useful :)

In the interim I'll use this workaround.

**Comment by fir3pho3nixx** [comment]
@eben-roux - I hastily typed out this code before catching a flight. I have done a little more due diligence and investigated whether we could simply use the `CanResolve` public API. This is a little more tricky because it requires a CreationContext eccetera. 

If you are willing to contribute a PR I can recommend the place to put the code and the test. Details below:

 - Fork the project

 - Add an `Extensions` folder to the following location along with the class mentioned above: https://github.com/castleproject/Windsor/tree/master/src/Castle.Windsor/MicroKernel/Resolvers

 - Add the test to the following folder: https://github.com/castleproject/Windsor/tree/master/src/Castle.Windsor.Tests/SpecializedResolvers

(It is the only determinable place I can find right now, perhaps just renaming it to resolvers might be a good shout). 

- Update CHANGELOG.md

Under an `Unreleased` section at the top there is already an `Enhancements` section. Add a short description along with your github handle and issue id. 

- Then people a lot smarter than me will review your PR. 

I am busy trying to get other PR's through which have been knocking about for ages, so I dont have time. Good luck and look forward to seeing your name on the committer list! :)

**Comment by eben-roux** [comment]
I'm currently swamped with my own work too but should I get some time I'll certainly submit a PR.
