### ISSUE TITLE
Registering Classes.FromThisAssembly() doesn't do anything

### ISSUE THREAD

**Issue by danquist** [castleproject/Windsor#374]
Trying to register all classes with the following syntax does nothing, although it compiles just fine and there's nothing obvious to indicate why it wouldn't register all types in my assembly.

```c#
container.Register(Classes.FromThisAssembly());
```

The *correct* syntax, I've finally discovered, is to use the `.Pick()` descriptor

```c#
container.Register(Classes.FromThisAssembly().Pick());
```
It seems to me that that the registration should either default to use Pick() if no other descriptor is provided or throw an exception indicating the operation isn't allowed. A better solution would be, if possible, to prevent passing in the return type of any `FromAssembly())` method into the registration method, although I suspect that would be fairly more complicated.

**Comment by jonorossi** [comment]
The problem here is that the `FromDescriptor` that you're fluently building has no criteria so doesn't register anything. Defaulting to everything matching `System.Object` which is what `Pick` does is unlikely what most people would want, I would expect it is uncommon to just register any and every public class in your assembly, users should probably be encouraged to specify a filter like `.BasedOn<ISomething>`.

https://github.com/castleproject/Windsor/blob/317d7e0e638ffe95f880ccb3ba44bed670c0dc71/src/Castle.Windsor/MicroKernel/Registration/FromDescriptor.cs#L173-L178

I can't think of a reason anyone would not specify a criteria of some kind, so throwing an exception mentioning `Pick` is probably a good idea. `FromDescriptor` implements `IRegistration` so we can't block passing it in.

**Comment by jonorossi** [comment]
@danquist did you get a chance to set up your environment? Let us know if you get stuck.

**Comment by danquist** [comment]
Just got some time to focus on this, actually. Cloned project and built with no issues so half the battle is won.

**Comment by fir3pho3nixx** [comment]
Closing as non-parte.
