### ISSUE TITLE
Need to integrate Castle.Core vNext

### ISSUE THREAD

**Issue by fir3pho3nixx** [castleproject/Windsor#425]
Need to integrate https://github.com/castleproject/Core/issues/376

**Comment by jonorossi** [comment]
@fir3pho3nixx what is this issue for? The title and link to an issue doesn't explain anything, while the linked issue is about deprecating `Lock` related types and members, no new public API was added. `Lock` usage in Windsor can be replaced at anytime, and I don't think Windsor uses `ModuleScope.DefineType` so won't need to use a new interface.

**Comment by fir3pho3nixx** [comment]
Sorry have not been following this as closely as I should. This a place holder to have another look. I will stop using the issue tracker as a Todo list. 

Just wanted to be sure there were no breaking changes. 

Sorry jonno

**Comment by fir3pho3nixx** [comment]
Any tips for how you track things? Could do with some advice. 

Also time with you is sparse and you are getting annoyed with your perception of my lack of focus. My interests and yours are not always aligned. Purely a comms problem. Dipping in and out of context is hard to establish from words scattered around issues everywhere. 

Can we please focus on getting aspnet core out? I need your attention for a bit. 

I would send you an email about these things but you are busy. Chewing my ass out for relevance on issues is not helping either.

**Comment by fir3pho3nixx** [comment]
> Yes my time is limited but please help me help you. I've mentioned it before that I live on GitHub email notifications, so when I read those and then open the issue/pull request to find those comments have been deleted or edited to something completely different it makes it really hard for me to keep track of things, I then have to search around the whole issue to work out what I've missed, and in this situation I often just close the tab and defer it to later and get through issues that should be quicker to sort out. I think you might have picked up on me doing this with some of your issues/PRs recently, I'm not picking favourites just only have so much time attacking my notifications each day.

Right... so don’t fuck up and re-write comments Gavin. If that is annoying you all I can offer is I will try. I personally avoid email and use the Github dashboard. I get a shit tonne useless email daily. Trying to sift through that stuff is a complete waste of my time. If people are editing their issues I would take it as a sign of diligence, not something to be picked at because it is messing with your email workflow.

**Comment by fir3pho3nixx** [comment]
Let crack on. 👍

**Comment by jonorossi** [comment]
> Right... so don’t fuck up and re-write comments Gavin. If that is annoying you all I can offer is I will try. [..] If people are editing their issues I would take it as a sign of diligence, not something to be picked at because it is messing with your email workflow.

> [..] It offers people the means to edit their posts, and I find it unreasonable to expect people not to use that facility. It also allows people to get notifications, and reply to posts, through email. It's also unreasonable to expect people not to use that. [..]
>
> For the email-using folks like e.g. @jonorossi [..]

@fir3pho3nixx @stakx I feel like both of you twisted my words, I didn't and have never said not to edit posts, I actually prefer people to fix mistakes in posts to ensure their intent is conveyed clearly. I said exactly this:

> I live on GitHub email notifications, so when I read those and then open the issue/pull request to find those comments have been deleted or edited to something completely different it makes it really hard for me to keep track of things

Nothing more. I've never replied to a GitHub issue by email before and you'd know this because the little email icon never shows next to my posts. I use email notifications to keep up on what is happening while doing other things or waiting somewhere, e.g. while eating breakfast, out waiting for something, in between things. This allows me to use time otherwise wasted and also to think about what gets posted until I get to replying (I try to provide useful replies even though I usually take longer to reply), in which I always re-read comments before replying, if I didn't re-read how would I have noticed comments completely changing. Some "email-using folk" shouldn't be seen as a negative, I use the tools available to me the best way I think I can.

What I should have written is: if you want to completely change a comment to something different, can you please add a new comment and delete the old one, at least then I'll get an email notification so the email notifications make some sense. I really don't want to get hung up on this, it was a minor remark in this thread.

> For that reason, I would like to ask you to prioritise @fir3pho3nixx' work on ASP.NET Core, so we can get this shipped

As far as I am aware the ASP.NET Core work was finished ready for a beta release nearly a month ago, we are stuck going back and forth on a recently proposed change to the public API of `IWindsorContainer.Resolve` overloads, something I don't think should be changed with haste. I'll reply to that issue/PR next.

**Comment by fir3pho3nixx** [comment]
@jonorossi. Just to be clear the way you came back on this issue after ignoring open questions on my live PR’s seems a bit out whack mate. So let’s stop stirring the hornets nest. Bygones, move on. 

Also V5 seemed like a reasonable place to make breaking changes. You also suggested I look into this issue on the V5 release issue. So I am only doing what you asked. Clearly I am not doing a great job and you are not best pleased. Whatever man, I can’t read your mind.
