### ISSUE TITLE
Problems with Arguments

### ISSUE THREAD

**Issue by ronprowse** [castleproject/Windsor#491]
Using Windsor V5.0.0 after upgrading now the constructor arguments are no longer compile 
container.Resolve<OrdersReader>( new Arguments(new { Endpoint =  "XXXX" });

this works in V4.1.1. on but I cant find any solution or documentation covering this feature

**Comment by jonorossi** [comment]
The breaking changes to the `Arguments` class in v5 are mentioned as breaking changes in the changelog: https://github.com/castleproject/Windsor/blob/master/CHANGELOG.md#500-beta001-2018-10-26

The documentation for the `Arguments` class was updated: https://github.com/castleproject/Windsor/blob/master/docs/arguments.md

Constructors were removed because ambiguous object types couldn't be passed to it while a constructor accepts `System.Object`, you can now use:
- `new Arguments().AddProperties(new { Endpoint = "XXXX" })`, or
- `Arguments.FromProperties(new { Endpoint = "XXXX" })`
