### ISSUE TITLE
LifeStyle.PerWebRequest gone in windsor 5

### ISSUE THREAD

**Issue by dagda1** [castleproject/Windsor#509]
I am looking at some old code for the [castle.facilities.hibernate](https://github.com/haf/Castle.Facilities.NHibernate/blob/master/src/Castle.Facilities.NHibernate/NHibernateFacility.cs#L297) facility and I am trying to upgrade it to castle.windsor 5 erroring because of this line

```c#
return registration.Named(baseName + SessionPWRSuffix).LifeStyle.PerWebRequest;
```

In my limited knowledge, I have come up with this:

```cs
return registration.Named(baseName + SessionPWRSuffix).LifeStyle
                            .Scoped<WebRequestScopeAccessor>();
```

Is this correct?

**Comment by jonorossi** [comment]
Check out the docs for the System.Web facility, the System.Web integration was moved out of Windsor's core into this facility:
https://github.com/castleproject/Windsor/blob/master/docs/systemweb-facility.md

Basically, add the `Castle.Facilities.AspNet.SystemWeb` package/assembly, and use the `LifestylePerWebRequest()` extension method instead of the `PerWebRequest` property. What you've guessed (i.e. using the scoped lifestyle and `WebRequestScopeAccessor` is what the extension method will set up for you).
