### ISSUE TITLE
Castle.Core has made Castle.Core.Internal.Lock obsolete

### ISSUE THREAD

**Issue by generik0** [castleproject/Windsor#565]
HI @jonorossi 

Castle.Core has removed made Castle.Core.Internal.Lock obsolete. It is used in SimpleThreadSafeCollection and SimpleThreadSafeSet.
Recommends migration to System.Threading.ReaderWriterLockSlim that is also in net45++

Thoughts, should we migrate? Right now, the build will fail due to warning, if Castle.Core is updated.

EDIT: After pulling 4.4.1, Lock is actually removed, this change is required

**Comment by jonorossi** [comment]
`SimpleThreadSafeCollection` should be changed to use a `ReaderWriterLockSlim` directly. We used to use the `Lock` class in Castle.Core because Silverlight doesn't have RWLS. There is no need for this abstraction anymore.

Castle.Core's `SynchronizedDictionary` (internal class) is an example of a class that no longer uses the `Lock` abstraction.

**Comment by generik0** [comment]
HI @jonorossi when you have time, please review PR
