### ISSUE TITLE
How to upgrade Castle.Windsor 2.5 to 5.1.1 along with Castle.Services.Transaction 2.5

### ISSUE THREAD

**Issue by dpadmja** [castleproject/Windsor#586]
Our project has been using https://github.com/castleproject-deprecated/Castle.Facilities.NHibernateIntegration-READONLY project for long.
We are trying to upgrade this project with newer version of castle.windsor dll. We are not able to find out the replacements for components like: ISynchronization, IResource, ITransactionManager, transaction.Context, transaction.IsolationMode, transaction.IsAmbient, new SessionDisposeSynchronization(session), new StatelessSessionDisposeSynchronization(session) .

![image](https://user-images.githubusercontent.com/40098145/102622293-d0c56880-4166-11eb-9ece-8d91416357b4.png)

Could you please help here?

**Comment by jonorossi** [comment]
You are using a library that hasn't been modified in nearly 10 years, looks like you haven't got a reference to Castle Transactions. There are no replacements for those things, both libraries are just deprecated because no one wanted to maintain it.

- https://github.com/castleproject-deprecated/Transactions
- https://github.com/castleproject-deprecated/Castle.Windsor.Facilities/tree/master/src

**Comment by lars-hakansson** [comment]
@jonorossi I thought this is a replacement for Castle Transactions. The solution I am upgrading depends heavily on TransactionAttribute from Castle Transactions and my gameplan is to remove Castle Transactions and add this instead! Wrong? Switch one attribute with another..
