### ISSUE TITLE
Question: Is Castle Windsor still going to be maintained?

### ISSUE THREAD

**Issue by fancycoconut** [castleproject/Windsor#587]
Hi,
Just a quick question as the title says: Is this project still going to be actively maintained?

**Comment by Servox3** [comment]
Lately, voluntary (as allways) developers have worked quite a bit on lifting the software:
[https://github.com/castleproject/Windsor/pulse/monthly](url)

**Comment by jonorossi** [comment]
As @Servox3 mentioned, there has been quite a bit of activity over the last few months with our last release less than 2 weeks ago.

People scratch their own itch, if something doesn't work for you or you'd like something to be better for your use case, please contribute; even a unit test for a scenario or documentation updates helps everyone. There is obviously no vendor here giving you 10 years of support, but Windsor has been going since around 2004.
