### ISSUE TITLE
Resolve component implementing single generic interface throws ArgumentException

### ISSUE THREAD

**Issue by ezsilmar** [castleproject/Windsor#75]
I'd like to resolve component which implements generic interface with different generic parameters. My code:

``` c#
    public interface IOuterService<T, U> : ICanBeResolvedByContainer
    {
    }

    public interface IWrap1<T> : ICanBeResolvedByContainer
    {
    }

    public interface IWrap2<T> : ICanBeResolvedByContainer
    {
    }

    public interface IService1<T, U> : IOuterService<IWrap1<T>, U>
    {
    }

    public interface IService2<T, U> : IOuterService<IWrap2<T>, U>
    {
    }

    public class Component<T, U> : IService1<T, U>, IService2<T, U>
    {
    }
```

Then let's register everything which implements ICanBeResolvedByContainer:

``` c#
    var container = new WindsorContainer();
    container.Register(
        Classes
            .FromAssemblyContaining<ICanBeResolvedByContainer>()
            .BasedOn<ICanBeResolvedByContainer>()
            .WithServiceFromInterface(typeof (ICanBeResolvedByContainer))
            .WithServiceSelf());
    var dep = container.Resolve<Component<int, int>>();
```

The last line throws ArgumentException: An item with the same key has already been added.

Expected behavior: resolve or throw meaningful exception.

My investigations lead to problem in [DefaultGenericHandler.EnsureInterfaceMappingInitialized](https://github.com/castleproject/Windsor/blob/016730de012f15985410fb33e2eb907690fe5a28/src/Castle.Windsor/MicroKernel/Handlers/DefaultGenericHandler.cs#L472). GetGenericTypeDefinition is used here as dictionary key, and there are obviously two similar keys in this case: typeof(IOuterService<,>). 

Is this just a not implemented case?

**Comment by kkozmic** [comment]
Without running your test or looking at any code, it looks like it might be a bug. Part of the problem appears to be related to the fact that semi-open generic types are involved, but ideally it should just work.

**Comment by dalefrancis88** [comment]
Hey,

I created a fix for this. https://github.com/castleproject/Windsor/pull/81

**Comment by ezsilmar** [comment]
dalefrancis88, thank you for the fix.

I've tried it and found this case (setup is the same):

```c#
   Container.Resolve<IOuterService<IWrap1<int>, int>>()
```

Expected behavior is to return Component< int, int>. However ComponentNotFoundException is thrown. The problem is in SupportsAssignable(Type service) method of DefaultGenericHandler: it tries to check Component< IWrap< int>, int> and fails. This case seems to be much more complicated, maybe it should be another issue.

**Comment by dalefrancis88** [comment]
Interesting. That might have something to do with IWrap not having a direct implementation but given that its generics I am not sure. 

Should be at a computer in an hour. I'll check it out then

-----Original Message-----

**Comment by dalefrancis88** [comment]
Hey,

I forgot until i seen the code but the reason you're getting component not found is that your registration is missing .WithServiceAllInterfaces() 

However when you add this in there are more issues, trying to work through those

**Comment by dalefrancis88** [comment]
Hey,

This is the error i get... 

System.InvalidCastException : Unable to cast object of type 'CastleTests.Generics.Component`2[CastleTests.Generics.IWrap1`1[System.Int32],System.Int32]' to type 'CastleTests.Generics.IOuterService`2[CastleTests.Generics.IWrap1`1[System.Int32],System.Int32]'

So it appears to be a variance issue. If you try to resolve a service of type T the resulting component has to be of type T. So when it tries to return a Component<int, int> it cannot cast it to the typeof IOuterService<IWrap1<int>, int> because T is not marked as covariant. 
It is able to resolve the component, its just in the casting and returning in resolve that fails. You can see this if you resolve using the below...

var componentWrap1 = this.Container.Resolve(typeof(IOuterService<IWrap1<int>, int>));

The major problem though is that this means that you cannot have IOuterService<IWrap1<int>, int> as a constructor parameter as it calls the same code as resolve<IOuterService<IWrap1<int>, int>>.

I tried to create a generic factory with the parameter marked as covariant but that still seems to run through the same code, which is to be expected.

These are my thoughts, i could be wrong, i am still looking into it.

**Comment by dalefrancis88** [comment]
Hey,

This has been bugging the last few days. Been letting it roll around in my head because the above just seemed wrong. If it was the case there would be far more issues.

I wrote some more tests this morning and realised if you register the IOuterService part directly it works fine. Which means i was wrong. 

So it seems that it is the registration code that is causing this. My guess is the concept of open generics with open generics inside.

Out of curiosity what is your real world example of this? I am a huge fan of generics and don't think i have ever needed a combination like this.

**Comment by kkozmic** [comment]
Can we close this issue @ezsilmar? Also, like @dalefrancis88 I would be interested to hear what is your real life scenario for this
