### ISSUE TITLE
Wrong documentation for typed factory facility

### ISSUE THREAD

**Issue by sloncho** [castleproject/Windsor#82]
[The documantation for "Get" methoid behavior](http://docs.castleproject.org/Windsor.Typed-Factory-Facility-interface-based-factories.ashx#Get_methods_lookup_components_by_name_4) is misleading. It still says that the default behavior is to fallback to type resolution if the get by name fails.

Apperantly this have been changed with commit 213d45dbaca7b3e0cd2ce06677062974311dd589 and is no longer valid for v3 and up.

**Comment by kkozmic-seek** [comment]
Well spotted. Care to fix the mistake?

**Comment by sloncho** [comment]
I'd like to, but I fail in the registration process for docs wiki. It says "invalid password" w/o any explanation what are the password rules. I tried few passwords with complexity of my linking and it still fails.

**Comment by kkozmic-seek** [comment]
hmm interesting. @jonorossi any idea what's happened there?

**Comment by jonorossi** [comment]
I didn't see anything in the logs.

@sloncho I've manually created a user for you. Give the password reset a go, if that doesn't work I'll reset the password and email it to you.

**Comment by sloncho** [comment]
@jonorossi - thanks.

I just tried to reset with few randomly generated passwords from my password tool. An example is "Prx>c|)OZ1Y%", and they fail.

The only message is "Invalid password".

What constitutes "valid" password?

**Comment by jonorossi** [comment]
Screwturn is configured to require a password matching this: `^\w[\w~!@#$%^\(\)\[\]\{\}\.,=\-_\ ]{5,25}$`. So it looks like it doesn't like the `>` and `|` (pipe).

OT: We really need to migrate from Screwturn Wiki, it is long dead. I know I've said it many times before and I've been meaning to do it for years, but this time you've pushed me to actually get it done. Yesterday I started with MonoRail because if I mess it up most people won't mind, I'll get Windsor done after I'm done with MonoRail.
https://github.com/castleproject/MonoRail/wiki

**Comment by jonorossi** [comment]
@sloncho I've migrated all of the documentation to markdown in this git repo, you should be able to easily make the change here: https://github.com/castleproject/Windsor/blob/master/docs/typed-factory-facility-interface-based.md

**Comment by sloncho** [comment]
@jonorossi I'm doing the change. Just wondering how deep should I go.

Do I mention that this was the old behavior?
Do I provide info about the fallbackToResolveByTypeIfNameNotFound for backward compatibility (the ndoc says it should not be used).

Is it just enough to remove the wrong statement?

**Comment by jonorossi** [comment]
@sloncho 3.0.0 was released many years ago, no need to worry about mentioning the behaviour has changed, just remove the wrong statement.

You could just copy the text from BreakingChanges.txt that mentions the behaviour of `fallbackToResolveByTypeIfNameNotFound` and `getMethodsResolveByName`, however I'd just let people look at the class if they need those non-default options rather than making the docs bigger.

**Comment by kkozmic-seek** [comment]
yup, agreed with @jonorossi 

This is a corner case behaviour and we'd rather steer people away from using it, so I'd leave it out from the docs. Intellisense and naming should be enough to guide the brave ones who want to try it
