### ISSUE TITLE
Sample Project does not work

### ISSUE THREAD

**Issue by petersmax** [castleproject/Windsor#87]
Just a heads up, the sample project does not work at all. Tried VS2010, 2012, 2013.

**Comment by jonorossi** [comment]
@petersmax which sample project are you referring to, and what error are you getting or how does it not work?

**Comment by petersmax** [comment]
The ToBeSeen mvc 3 sample project

**Comment by petersmax** [comment]
https://github.com/kkozmic/ToBeSeen

and while I realize that you are not the owner of that project, that is listed on your site.

**Comment by jonorossi** [comment]
Yep, @kkozmic wrote it and also wrote the tutorial. The actual sample code project is definitely un[der]maintained, definitely leave this issue open and we'll get around to bringing it up to scratch, or feel free to send pull requests to that repo. Thanks.

**Comment by petersmax** [comment]
Well I am trying to replicate what he did, but I compared to you guys am incredibly new. If I come up with something substantial, I will push that through. Very nice work you guys do.

**Comment by petersmax** [comment]
also, related issue, would like to submit a sample project update for the project's documentation. unable to do that.

**Comment by petersmax** [comment]
submitted a fork with the fixes... now it works

**Comment by jonorossi** [comment]
@petersmax I think you might have misunderstood how forks and pull requests work because we didn't receive a pull request from you. Forking a repository just makes a copy for you under your name, to send those changes back upstream you have to send a pull request which is just a two click process.

I did look at your fork which has a branch with changes to `basic-tutorial.md` which is here (
https://github.com/petersmax/Windsor/tree/patch-1). Just note that I updated that same tutorial the other day to include the using statements because someone on StackOverflow asked for them.

**Comment by petersmax** [comment]
I was missing the extra step of actually creating the pull request, while
the version you ported is good I had a few more corrections. I thought a
little contribution was in order. But yes thank you for informing me.


____________
Maximus Peters
