### ISSUE TITLE
Add support to immutable collections

### ISSUE THREAD

**Issue by mfidemraizer** [castleproject/Windsor#94]
It would be very useful that Castle Windsor could support `System.Collections.Immutable` in typed factories since it seems like returning an immutable list of implementations is more meaningful than returning mutable collections or a typed array:

```
    public interface ISampleFactory
    {
         ImmutableList<ISome> ListAllSomes();
    }
```

**Comment by dalefrancis88** [comment]
Hey,

The way I understand it is that the types that get returned from a factory need to be interfaces. This includes collections. 

https://github.com/castleproject/Windsor/blob/master/docs/typed-factory-facility-interface-based.md

However even adding an IImmutableList instead of ImmutableList won't work because the constructor of ImmutableList is not public. On top of that, for this to work, CW would need to take a dependency on that particular package which not everyone needs.

For a quick/dirty solution, you could change it to IList<ISome> and then create the Immutable list from that. 

If you have enough time than you could create your own facility/resolver that could do this as well.

**Comment by fir3pho3nixx** [comment]
The OP was answered by @dalefrancis88
